//lib/color-palettes.ts

export const predefinedPalettes = [
  {
    id: "linkedin",
    name: "LinkedIn",
    primaryColor: "#0077B5",
    secondaryColor: "#ffffff",
    accentColor: "#00a0dc",
    backgroundColor: "#f3f6f8",
  },
  {
    id: "professional",
    name: "Professional",
    primaryColor: "#2c3e50",
    secondaryColor: "#ecf0f1",
    accentColor: "#3498db",
    backgroundColor: "#ffffff",
  },
  {
    id: "creative",
    name: "Creative",
    primaryColor: "#6b46c1",
    secondaryColor: "#ffffff",
    accentColor: "#f56565",
    backgroundColor: "#faf5ff",
  },
  {
    id: "dark",
    name: "Dark",
    primaryColor: "#e2e8f0",
    secondaryColor: "#a0aec0",
    accentColor: "#4299e1",
    backgroundColor: "#1a202c",
  },
  {
    id: "nature",
    name: "Nature",
    primaryColor: "#2f855a",
    secondaryColor: "#ffffff",
    accentColor: "#68d391",
    backgroundColor: "#f0fff4",
  },
  {
    id: "sunset",
    name: "Sunset",
    primaryColor: "#ed8936",
    secondaryColor: "#ffffff",
    accentColor: "#f6ad55",
    backgroundColor: "#fffaf0",
  },
  {
    id: "ocean",
    name: "Ocean",
    primaryColor: "#2b6cb0",
    secondaryColor: "#ebf8ff",
    accentColor: "#63b3ed",
    backgroundColor: "#ebf8ff",
  },
  {
    id: "monochrome",
    name: "Monochrome",
    primaryColor: "#1a202c",
    secondaryColor: "#4a5568",
    accentColor: "#718096",
    backgroundColor: "#f7fafc",
  },
  {
    id: "vibrant",
    name: "Vibrant",
    primaryColor: "#805ad5",
    secondaryColor: "#ffffff",
    accentColor: "#d53f8c",
    backgroundColor: "#faf5ff",
  },
];
